#The language to default to if a player's client is set to a non-supported language.
#If you're going to change this, make sure to set it lo one supported by this plugin or to an existing custom one
#inside the ./lang folder.
defaultLanguage: "en"

#If a player leaves the game, how long to keep their session alive, so they don't have to re-enter their password.
#as long as they re-join from the same IP address. In seconds. 0 or less will disable this feature.
sessionHoldTime: 300

#Wheather or not to allow a player to leave and re-join the server from a different platform (Java, Bedrock) without
#re-entering the password, withing the timeframe specified bellow, and from the same IP address.
crossPlatformSessions: false

failed_login_count:
  #If true, a player's account will be locked and access to the server will be denied after entering the wrong
  #password a certain amount of times defined by the settings that follow.
  accountLock: false
  #How many failed login attempts to star showing the Odd amount fo retried error message.
  odd: 3
  #How many failed login attempts over the above setting to warn the player about the account being locked.
  #accountLock must be true.
  warn: 3
  #How many failed login attempts over the above setting to actually lock the account.
  #accountLock must be true. Must be grater than 0.
  lock: 3

password_format:
  min_length: 4
  max_length: 12